/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountMinimalLayoutRouteImport } from './routes/account/_minimalLayout'
import { Route as AccountAppLayoutRouteImport } from './routes/account/_appLayout'
import { Route as AccountMinimalLayoutIndexRouteImport } from './routes/account/_minimalLayout/index'
import { Route as AccountMinimalLayoutSignInRouteImport } from './routes/account/_minimalLayout/sign-in'
import { Route as AccountMinimalLayoutResetPasswordRouteImport } from './routes/account/_minimalLayout/reset-password'
import { Route as AccountMinimalLayoutBrandingRouteImport } from './routes/account/_minimalLayout/branding'
import { Route as AccountAppLayoutSubRouteImport } from './routes/account/_appLayout/$sub'

const AccountRouteImport = createFileRoute('/account')()

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountMinimalLayoutRoute = AccountMinimalLayoutRouteImport.update({
  id: '/_minimalLayout',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAppLayoutRoute = AccountAppLayoutRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMinimalLayoutIndexRoute =
  AccountMinimalLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AccountMinimalLayoutRoute,
  } as any)
const AccountMinimalLayoutSignInRoute =
  AccountMinimalLayoutSignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => AccountMinimalLayoutRoute,
  } as any)
const AccountMinimalLayoutResetPasswordRoute =
  AccountMinimalLayoutResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => AccountMinimalLayoutRoute,
  } as any)
const AccountMinimalLayoutBrandingRoute =
  AccountMinimalLayoutBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AccountMinimalLayoutRoute,
  } as any)
const AccountAppLayoutSubRoute = AccountAppLayoutSubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => AccountAppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/account': typeof AccountMinimalLayoutRouteWithChildren
  '/account/$sub': typeof AccountAppLayoutSubRoute
  '/account/branding': typeof AccountMinimalLayoutBrandingRoute
  '/account/reset-password': typeof AccountMinimalLayoutResetPasswordRoute
  '/account/sign-in': typeof AccountMinimalLayoutSignInRoute
  '/account/': typeof AccountMinimalLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof AccountMinimalLayoutIndexRoute
  '/account/$sub': typeof AccountAppLayoutSubRoute
  '/account/branding': typeof AccountMinimalLayoutBrandingRoute
  '/account/reset-password': typeof AccountMinimalLayoutResetPasswordRoute
  '/account/sign-in': typeof AccountMinimalLayoutSignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/account': typeof AccountRouteWithChildren
  '/account/_appLayout': typeof AccountAppLayoutRouteWithChildren
  '/account/_minimalLayout': typeof AccountMinimalLayoutRouteWithChildren
  '/account/_appLayout/$sub': typeof AccountAppLayoutSubRoute
  '/account/_minimalLayout/branding': typeof AccountMinimalLayoutBrandingRoute
  '/account/_minimalLayout/reset-password': typeof AccountMinimalLayoutResetPasswordRoute
  '/account/_minimalLayout/sign-in': typeof AccountMinimalLayoutSignInRoute
  '/account/_minimalLayout/': typeof AccountMinimalLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/account/$sub'
    | '/account/branding'
    | '/account/reset-password'
    | '/account/sign-in'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/account/$sub'
    | '/account/branding'
    | '/account/reset-password'
    | '/account/sign-in'
  id:
    | '__root__'
    | '/account'
    | '/account/_appLayout'
    | '/account/_minimalLayout'
    | '/account/_appLayout/$sub'
    | '/account/_minimalLayout/branding'
    | '/account/_minimalLayout/reset-password'
    | '/account/_minimalLayout/sign-in'
    | '/account/_minimalLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountRoute: typeof AccountRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/_minimalLayout': {
      id: '/account/_minimalLayout'
      path: ''
      fullPath: '/account'
      preLoaderRoute: typeof AccountMinimalLayoutRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/_appLayout': {
      id: '/account/_appLayout'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountAppLayoutRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/_minimalLayout/': {
      id: '/account/_minimalLayout/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountMinimalLayoutIndexRouteImport
      parentRoute: typeof AccountMinimalLayoutRoute
    }
    '/account/_minimalLayout/sign-in': {
      id: '/account/_minimalLayout/sign-in'
      path: '/sign-in'
      fullPath: '/account/sign-in'
      preLoaderRoute: typeof AccountMinimalLayoutSignInRouteImport
      parentRoute: typeof AccountMinimalLayoutRoute
    }
    '/account/_minimalLayout/reset-password': {
      id: '/account/_minimalLayout/reset-password'
      path: '/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountMinimalLayoutResetPasswordRouteImport
      parentRoute: typeof AccountMinimalLayoutRoute
    }
    '/account/_minimalLayout/branding': {
      id: '/account/_minimalLayout/branding'
      path: '/branding'
      fullPath: '/account/branding'
      preLoaderRoute: typeof AccountMinimalLayoutBrandingRouteImport
      parentRoute: typeof AccountMinimalLayoutRoute
    }
    '/account/_appLayout/$sub': {
      id: '/account/_appLayout/$sub'
      path: '/$sub'
      fullPath: '/account/$sub'
      preLoaderRoute: typeof AccountAppLayoutSubRouteImport
      parentRoute: typeof AccountAppLayoutRoute
    }
  }
}

interface AccountAppLayoutRouteChildren {
  AccountAppLayoutSubRoute: typeof AccountAppLayoutSubRoute
}

const AccountAppLayoutRouteChildren: AccountAppLayoutRouteChildren = {
  AccountAppLayoutSubRoute: AccountAppLayoutSubRoute,
}

const AccountAppLayoutRouteWithChildren =
  AccountAppLayoutRoute._addFileChildren(AccountAppLayoutRouteChildren)

interface AccountMinimalLayoutRouteChildren {
  AccountMinimalLayoutBrandingRoute: typeof AccountMinimalLayoutBrandingRoute
  AccountMinimalLayoutResetPasswordRoute: typeof AccountMinimalLayoutResetPasswordRoute
  AccountMinimalLayoutSignInRoute: typeof AccountMinimalLayoutSignInRoute
  AccountMinimalLayoutIndexRoute: typeof AccountMinimalLayoutIndexRoute
}

const AccountMinimalLayoutRouteChildren: AccountMinimalLayoutRouteChildren = {
  AccountMinimalLayoutBrandingRoute: AccountMinimalLayoutBrandingRoute,
  AccountMinimalLayoutResetPasswordRoute:
    AccountMinimalLayoutResetPasswordRoute,
  AccountMinimalLayoutSignInRoute: AccountMinimalLayoutSignInRoute,
  AccountMinimalLayoutIndexRoute: AccountMinimalLayoutIndexRoute,
}

const AccountMinimalLayoutRouteWithChildren =
  AccountMinimalLayoutRoute._addFileChildren(AccountMinimalLayoutRouteChildren)

interface AccountRouteChildren {
  AccountAppLayoutRoute: typeof AccountAppLayoutRouteWithChildren
  AccountMinimalLayoutRoute: typeof AccountMinimalLayoutRouteWithChildren
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAppLayoutRoute: AccountAppLayoutRouteWithChildren,
  AccountMinimalLayoutRoute: AccountMinimalLayoutRouteWithChildren,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AccountRoute: AccountRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
